library(dplyr)

MORTALIDADE_PRE_PANDEMIA_SAMPLE['CODMUNRES'] <- apply(MORTALIDADE_PRE_PANDEMIA_SAMPLE['CODMUNRES'], 1, regiao_por_codigo_uf)  
MORTALIDADE_DURANTE_PANDEMIA_SAMPLE['CODMUNRES'] <- apply(MORTALIDADE_DURANTE_PANDEMIA_SAMPLE['CODMUNRES'], 1, regiao_por_codigo_uf)                    

sum(MORTALIDADE_PRE_PANDEMIA_SAMPLE$CIRCOBITO == 2, na.rm = TRUE)
sum(MORTALIDADE_DURANTE_PANDEMIA_SAMPLE$CIRCOBITO == 2, na.rm = TRUE)
